apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: marx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: marx
spec:
spec:
  type: LoadBalancer
  externalIPs:
  - 54.236.57.197
  selector:
    app: my-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
